export enum Query {
  USER_CHARACTER = 'user_character',
  ALL_CHARACTERS = 'all_characters',
  ALL_PURCHASES = 'all_purchases',
  ALL_GUILDS = 'all_guilds',
  ALL_MARKET = 'all_market',
  PARTY = 'party',
  DISCORD = 'discord',
  ALL_GUILD_TASK = 'all_guild_task',
  GUILD = 'guild',
  BATTLE = 'battle',
  MAPS = 'maps',
  MAILBOX = 'mailbox',
  NOTIFICATIONS = 'notifications',
  ALL_PROFESSIONS = 'all_professions',
  GATHERING_NODES = 'gathering_nodes',
  RECIPES = 'recipes',
  SERVICE_OFFERS = 'service_offers',
}
